// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelCompany.API.Data;

#nullable disable

namespace TravelCompany.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609082011_f1")]
    partial class f1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelCompany.API.Models.Entities.ChiTietLichTrinh", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HoatDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<int>("NgayThu")
                        .HasColumnType("int");

                    b.Property<string>("ThongTinBuaAn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ThongTinKhachSan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaTour");

                    b.ToTable("ChiTietLichTrinh");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.DanhGiaTour", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("MaDatTour")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaDatTour");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("DanhGiaTour");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.DatTour", b =>
                {
                    b.Property<int>("MaDatTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDatTour"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCodeDat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaLich")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhiHuy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuongNguoi")
                        .HasColumnType("int");

                    b.Property<decimal>("TienConLai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienDatCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("cho_xac_nhan");

                    b.HasKey("MaDatTour");

                    b.HasIndex("MaCodeDat")
                        .IsUnique();

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaLich");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("DatTour", t =>
                        {
                            t.HasCheckConstraint("CK_DatTour_TrangThai", "TrangThai IN ('cho_xac_nhan','da_xac_nhan','da_dat_coc','da_thanh_toan','da_huy')");
                        });
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.DiemDen", b =>
                {
                    b.Property<int>("MaDiemDen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiemDen"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDiemDen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ThanhPho")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDiemDen");

                    b.ToTable("DiemDen");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<decimal>("ConLai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DaThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaCodeHoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaDatTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("chua_thanh_toan");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaCodeHoaDon")
                        .IsUnique();

                    b.HasIndex("MaDatTour")
                        .IsUnique();

                    b.ToTable("HoaDon", t =>
                        {
                            t.HasCheckConstraint("CK_HoaDon_TrangThai", "TrangThai IN ('chua_thanh_toan','thanh_toan_mot_phan','da_thanh_toan','da_huy')");
                        });
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiKhach")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("moi");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHang", t =>
                        {
                            t.HasCheckConstraint("CK_KhachHang_GioiTinh", "GioiTinh IN ('Nam','Nữ','Khác')");

                            t.HasCheckConstraint("CK_KhachHang_LoaiKhach", "LoaiKhach IN ('moi','than_thiet','vip')");
                        });
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.LichKhoiHanh", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<decimal>("GiaTour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKhoiHanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoChoConLai")
                        .HasColumnType("int");

                    b.Property<int>("SoChoToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("con_cho");

                    b.HasKey("MaLich");

                    b.HasIndex("MaTour");

                    b.ToTable("LichKhoiHanh", t =>
                        {
                            t.HasCheckConstraint("CK_LichKhoiHanh_TrangThai", "TrangThai IN ('con_cho','het_cho','da_khoi_hanh','da_huy')");
                        });
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.LichSuDatTour", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaDatTour")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiCu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThaiMoi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaDatTour");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("LichSuDatTour");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.NguoiDiTour", b =>
                {
                    b.Property<int>("MaNguoiDi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDi"));

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaDatTour")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoCCCD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNguoiDi");

                    b.HasIndex("MaDatTour");

                    b.ToTable("NguoiDiTour");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("hoat_dong");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("nhan_vien");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("TaiKhoan", t =>
                        {
                            t.HasCheckConstraint("CK_TaiKhoan_TrangThai", "TrangThai IN ('hoat_dong','khoa')");

                            t.HasCheckConstraint("CK_TaiKhoan_VaiTro", "VaiTro IN ('quan_tri','quan_ly','nhan_vien','ke_toan')");
                        });
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaDatTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("thanh_cong");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaDatTour");

                    b.ToTable("ThanhToan", t =>
                        {
                            t.HasCheckConstraint("CK_ThanhToan_LoaiThanhToan", "LoaiThanhToan IN ('dat_coc','thanh_toan_day_du','thanh_toan_con_lai','hoan_tien')");

                            t.HasCheckConstraint("CK_ThanhToan_PhuongThuc", "PhuongThuc IN ('tien_mat','chuyen_khoan','the','vi_dien_tu')");

                            t.HasCheckConstraint("CK_ThanhToan_TrangThai", "TrangThai IN ('thanh_cong','that_bai','cho_xu_ly')");
                        });
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.Tour", b =>
                {
                    b.Property<int>("MaTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTour"));

                    b.Property<decimal>("GiaCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaCodeTour")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaDiemDen")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoNgay")
                        .HasColumnType("int");

                    b.Property<string>("TenTour")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("dang_mo");

                    b.HasKey("MaTour");

                    b.HasIndex("MaCodeTour")
                        .IsUnique();

                    b.HasIndex("MaDiemDen");

                    b.ToTable("Tour", t =>
                        {
                            t.HasCheckConstraint("CK_Tour_TrangThai", "TrangThai IN ('dang_mo','tam_ngung','da_huy')");
                        });
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.ChiTietLichTrinh", b =>
                {
                    b.HasOne("TravelCompany.API.Models.Entities.Tour", "Tour")
                        .WithMany("ChiTietLichTrinhs")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.DanhGiaTour", b =>
                {
                    b.HasOne("TravelCompany.API.Models.Entities.DatTour", "DatTour")
                        .WithMany("DanhGiaTours")
                        .HasForeignKey("MaDatTour")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelCompany.API.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("DanhGiaTours")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatTour");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.DatTour", b =>
                {
                    b.HasOne("TravelCompany.API.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("DatTours")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelCompany.API.Models.Entities.LichKhoiHanh", "LichKhoiHanh")
                        .WithMany("DatTours")
                        .HasForeignKey("MaLich")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelCompany.API.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("DatTours")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KhachHang");

                    b.Navigation("LichKhoiHanh");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.HoaDon", b =>
                {
                    b.HasOne("TravelCompany.API.Models.Entities.DatTour", "DatTour")
                        .WithOne("HoaDon")
                        .HasForeignKey("TravelCompany.API.Models.Entities.HoaDon", "MaDatTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatTour");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.LichKhoiHanh", b =>
                {
                    b.HasOne("TravelCompany.API.Models.Entities.Tour", "Tour")
                        .WithMany("LichKhoiHanhs")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.LichSuDatTour", b =>
                {
                    b.HasOne("TravelCompany.API.Models.Entities.DatTour", "DatTour")
                        .WithMany("LichSuDatTours")
                        .HasForeignKey("MaDatTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelCompany.API.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("LichSuDatTours")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DatTour");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.NguoiDiTour", b =>
                {
                    b.HasOne("TravelCompany.API.Models.Entities.DatTour", "DatTour")
                        .WithMany("NguoiDiTours")
                        .HasForeignKey("MaDatTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatTour");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.ThanhToan", b =>
                {
                    b.HasOne("TravelCompany.API.Models.Entities.DatTour", "DatTour")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaDatTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatTour");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.Tour", b =>
                {
                    b.HasOne("TravelCompany.API.Models.Entities.DiemDen", "DiemDen")
                        .WithMany("Tours")
                        .HasForeignKey("MaDiemDen")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DiemDen");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.DatTour", b =>
                {
                    b.Navigation("DanhGiaTours");

                    b.Navigation("HoaDon");

                    b.Navigation("LichSuDatTours");

                    b.Navigation("NguoiDiTours");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.DiemDen", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.KhachHang", b =>
                {
                    b.Navigation("DanhGiaTours");

                    b.Navigation("DatTours");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.LichKhoiHanh", b =>
                {
                    b.Navigation("DatTours");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.TaiKhoan", b =>
                {
                    b.Navigation("DatTours");

                    b.Navigation("LichSuDatTours");
                });

            modelBuilder.Entity("TravelCompany.API.Models.Entities.Tour", b =>
                {
                    b.Navigation("ChiTietLichTrinhs");

                    b.Navigation("LichKhoiHanhs");
                });
#pragma warning restore 612, 618
        }
    }
}
