// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyDuLich.Data;

#nullable disable

namespace QuanLyDuLich.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260623140758_f2")]
    partial class f2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.ChiTietLichTrinh", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaChiTiet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DiaDiem");

                    b.Property<string>("HoatDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HoatDong");

                    b.Property<int?>("MaTour")
                        .HasColumnType("int")
                        .HasColumnName("MaTour");

                    b.Property<int?>("NgayThu")
                        .HasColumnType("int")
                        .HasColumnName("NgayThu");

                    b.Property<string>("ThongTinBuaAn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ThongTinBuaAn");

                    b.Property<string>("ThongTinKhachSan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ThongTinKhachSan");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TieuDe");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaTour");

                    b.ToTable("ChiTietLichTrinh");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.DanhGiaTour", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDanhGia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int?>("MaDatTour")
                        .HasColumnType("int")
                        .HasColumnName("MaDatTour");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int")
                        .HasColumnName("MaKhachHang");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayDanhGia");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDung");

                    b.Property<int?>("SoSao")
                        .HasColumnType("int")
                        .HasColumnName("SoSao");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaDatTour")
                        .IsUnique()
                        .HasFilter("[MaDatTour] IS NOT NULL");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("DanhGiaTour");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.DatTour", b =>
                {
                    b.Property<int>("MaDatTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDatTour");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDatTour"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<string>("MaCodeDat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaCodeDat");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int")
                        .HasColumnName("MaKhachHang");

                    b.Property<int?>("MaLich")
                        .HasColumnType("int")
                        .HasColumnName("MaLich");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("MaTaiKhoan");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayDat");

                    b.Property<decimal?>("PhiHuy")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PhiHuy");

                    b.Property<int?>("SoLuongNguoi")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongNguoi");

                    b.Property<decimal?>("TienConLai")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TienConLai");

                    b.Property<decimal?>("TienDatCoc")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TienDatCoc");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TongTien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaDatTour");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaLich");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("DatTour");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.DiemDen", b =>
                {
                    b.Property<int>("MaDiemDen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDiemDen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiemDen"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<string>("QuocGia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("QuocGia");

                    b.Property<string>("TenDiemDen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenDiemDen");

                    b.Property<string>("ThanhPho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ThanhPho");

                    b.HasKey("MaDiemDen");

                    b.ToTable("DiemDen");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHoaDon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<decimal?>("ConLai")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ConLai");

                    b.Property<decimal?>("DaThanhToan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DaThanhToan");

                    b.Property<string>("MaCodeHoaDon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaCodeHoaDon");

                    b.Property<int?>("MaDatTour")
                        .HasColumnType("int")
                        .HasColumnName("MaDatTour");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayXuat");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TongTien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaDatTour")
                        .IsUnique()
                        .HasFilter("[MaDatTour] IS NOT NULL");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKhachHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HoTen");

                    b.Property<string>("LoaiKhach")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("LoaiKhach");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("MaTaiKhoan");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgaySinh");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SoDienThoai");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.LichKhoiHanh", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaLich");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<decimal?>("GiaTour")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GiaTour");

                    b.Property<int?>("MaTour")
                        .HasColumnType("int")
                        .HasColumnName("MaTour");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayKetThuc");

                    b.Property<DateTime>("NgayKhoiHanh")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayKhoiHanh");

                    b.Property<int?>("SoChoConLai")
                        .HasColumnType("int")
                        .HasColumnName("SoChoConLai");

                    b.Property<int?>("SoChoToiDa")
                        .HasColumnType("int")
                        .HasColumnName("SoChoToiDa");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaLich");

                    b.HasIndex("MaTour");

                    b.ToTable("LichKhoiHanh");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.LichSuDatTour", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaLichSu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HanhDong");

                    b.Property<int?>("MaDatTour")
                        .HasColumnType("int")
                        .HasColumnName("MaDatTour");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("MaTaiKhoan");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("TrangThaiCu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThaiCu");

                    b.Property<string>("TrangThaiMoi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThaiMoi");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaDatTour");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("LichSuDatTour");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.NguoiDiTour", b =>
                {
                    b.Property<int>("MaNguoiDi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNguoiDi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDi"));

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HoTen");

                    b.Property<int?>("MaDatTour")
                        .HasColumnType("int")
                        .HasColumnName("MaDatTour");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgaySinh");

                    b.Property<string>("SoCCCD")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SoCCCD");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SoDienThoai");

                    b.HasKey("MaNguoiDi");

                    b.HasIndex("MaDatTour");

                    b.ToTable("NguoiDiTour");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTaiKhoan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HoTen");

                    b.Property<string>("LoaiNhanVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LoaiNhanVien");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaNhanVien");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MatKhau");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThai");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("VaiTro");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaThanhToan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<string>("LoaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LoaiThanhToan");

                    b.Property<int?>("MaDatTour")
                        .HasColumnType("int")
                        .HasColumnName("MaDatTour");

                    b.Property<int?>("MaHoaDon")
                        .HasColumnType("int")
                        .HasColumnName("MaHoaDon");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayThanhToan");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PhuongThuc");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SoTien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaDatTour");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.Tour", b =>
                {
                    b.Property<int>("MaTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTour");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTour"));

                    b.Property<decimal?>("GiaCoBan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GiaCoBan");

                    b.Property<string>("MaCodeTour")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaCodeTour");

                    b.Property<int?>("MaDiemDen")
                        .HasColumnType("int")
                        .HasColumnName("MaDiemDen");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int?>("SoNgay")
                        .HasColumnType("int")
                        .HasColumnName("SoNgay");

                    b.Property<string>("TenTour")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenTour");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaTour");

                    b.HasIndex("MaDiemDen");

                    b.ToTable("Tour");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.ChiTietLichTrinh", b =>
                {
                    b.HasOne("QuanLyDuLich.Models.Entities.Tour", "Tour")
                        .WithMany("ChiTietLichTrinhs")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.DanhGiaTour", b =>
                {
                    b.HasOne("QuanLyDuLich.Models.Entities.DatTour", "DatTour")
                        .WithOne("DanhGiaTour")
                        .HasForeignKey("QuanLyDuLich.Models.Entities.DanhGiaTour", "MaDatTour")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyDuLich.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("DanhGiaTours")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DatTour");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.DatTour", b =>
                {
                    b.HasOne("QuanLyDuLich.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("DatTours")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyDuLich.Models.Entities.LichKhoiHanh", "LichKhoiHanh")
                        .WithMany("DatTours")
                        .HasForeignKey("MaLich")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyDuLich.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("DatTours")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KhachHang");

                    b.Navigation("LichKhoiHanh");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.HoaDon", b =>
                {
                    b.HasOne("QuanLyDuLich.Models.Entities.DatTour", "DatTour")
                        .WithOne("HoaDon")
                        .HasForeignKey("QuanLyDuLich.Models.Entities.HoaDon", "MaDatTour")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DatTour");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.KhachHang", b =>
                {
                    b.HasOne("QuanLyDuLich.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("QuanLyDuLich.Models.Entities.KhachHang", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.LichKhoiHanh", b =>
                {
                    b.HasOne("QuanLyDuLich.Models.Entities.Tour", "Tour")
                        .WithMany("LichKhoiHanhs")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.LichSuDatTour", b =>
                {
                    b.HasOne("QuanLyDuLich.Models.Entities.DatTour", "DatTour")
                        .WithMany("LichSuDatTours")
                        .HasForeignKey("MaDatTour")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuanLyDuLich.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("LichSuDatTours")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DatTour");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.NguoiDiTour", b =>
                {
                    b.HasOne("QuanLyDuLich.Models.Entities.DatTour", "DatTour")
                        .WithMany("NguoiDiTours")
                        .HasForeignKey("MaDatTour")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DatTour");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.ThanhToan", b =>
                {
                    b.HasOne("QuanLyDuLich.Models.Entities.DatTour", "DatTour")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaDatTour")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyDuLich.Models.Entities.HoaDon", "HoaDon")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaHoaDon");

                    b.Navigation("DatTour");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.Tour", b =>
                {
                    b.HasOne("QuanLyDuLich.Models.Entities.DiemDen", "DiemDen")
                        .WithMany("Tours")
                        .HasForeignKey("MaDiemDen")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DiemDen");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.DatTour", b =>
                {
                    b.Navigation("DanhGiaTour")
                        .IsRequired();

                    b.Navigation("HoaDon")
                        .IsRequired();

                    b.Navigation("LichSuDatTours");

                    b.Navigation("NguoiDiTours");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.DiemDen", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.HoaDon", b =>
                {
                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.KhachHang", b =>
                {
                    b.Navigation("DanhGiaTours");

                    b.Navigation("DatTours");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.LichKhoiHanh", b =>
                {
                    b.Navigation("DatTours");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.TaiKhoan", b =>
                {
                    b.Navigation("DatTours");

                    b.Navigation("KhachHang")
                        .IsRequired();

                    b.Navigation("LichSuDatTours");
                });

            modelBuilder.Entity("QuanLyDuLich.Models.Entities.Tour", b =>
                {
                    b.Navigation("ChiTietLichTrinhs");

                    b.Navigation("LichKhoiHanhs");
                });
#pragma warning restore 612, 618
        }
    }
}
